version: '3'
services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server/src:/app/src

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"
